# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1494272540);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 337920);
user_pref("browser.search.countryCode", "CH");
user_pref("browser.search.region", "CH");
user_pref("calendar.list.sortOrder", "28b318b5-75cb-4daa-9f43-7fef09796d6a");
user_pref("calendar.registry.28b318b5-75cb-4daa-9f43-7fef09796d6a.calendar-main-default", true);
user_pref("calendar.registry.28b318b5-75cb-4daa-9f43-7fef09796d6a.calendar-main-in-composite", true);
user_pref("calendar.registry.28b318b5-75cb-4daa-9f43-7fef09796d6a.name", "Home");
user_pref("calendar.registry.28b318b5-75cb-4daa-9f43-7fef09796d6a.type", "storage");
user_pref("calendar.registry.28b318b5-75cb-4daa-9f43-7fef09796d6a.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Africa/Abidjan");
user_pref("calendar.ui.version", 1);
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 114149);
user_pref("datareporting.sessions.current.main", 33357);
user_pref("datareporting.sessions.current.startTime", "1494272361062");
user_pref("datareporting.sessions.current.totalTime", 226);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D:4.7.8");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.8.0");
user_pref("extensions.lastPlatformVersion", "45.8.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-global\":{\"{e2fda1a4-762b-4020-b5ad-a41df1933103}\":{\"d\":\"/usr/lib/thunderbird/extensions/{e2fda1a4-762b-4020-b5ad-a41df1933103}\",\"e\":true,\"v\":\"4.7.8\",\"st\":1494269050000,\"mt\":1262304000000}}}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.rights.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 11);
user_pref("mailnews.database.global.datastore.id", "e2caafa7-5536-4a10-b87a-8bce009d1e2");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "45.8.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.telemetry.cachedClientID", "a628b975-4cca-473d-a8fd-40046df2f6f5");
user_pref("toolkit.telemetry.previousBuildID", "20170415143706");
