# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1494270949891");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1494274549891");
user_pref("browser.search.countryCode", "CH");
user_pref("browser.search.region", "CH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20170419042421");
user_pref("browser.slowStartup.averageTime", 9417);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage", "daylight.hamdygital.xyz");
user_pref("browser.startup.homepage_override.buildID", "20170419042421");
user_pref("browser.startup.homepage_override.mstone", "45.9.0");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1494357309487");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1494270909486");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 5880);
user_pref("datareporting.sessions.current.main", 1103);
user_pref("datareporting.sessions.current.sessionRestored", 6778);
user_pref("datareporting.sessions.current.startTime", "1494271185162");
user_pref("datareporting.sessions.current.totalTime", 10);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.0", "{\"s\":1494270906807,\"a\":9,\"t\":68,\"c\":true,\"m\":115,\"fp\":19097,\"sr\":18778}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1494270988907,\"a\":1,\"t\":16,\"c\":true,\"m\":48,\"fp\":7387,\"sr\":6686}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1494271165495,\"a\":0,\"t\":17,\"c\":true,\"m\":2273,\"fp\":6497,\"sr\":7144}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.9.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.9.0");
user_pref("extensions.lastPlatformVersion", "45.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib/firefox-esr/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1492669812000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox-esr/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.9.0\",\"st\":1492669808000}}}");
user_pref("gecko.buildID", "20170419042421");
user_pref("gecko.mstone", "45.9.0");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 24206);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1494271186);
user_pref("toolkit.telemetry.cachedClientID", "59fdbe99-accb-4174-b28e-b76e1cedcd2d");
user_pref("toolkit.telemetry.previousBuildID", "20170419042421");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
