#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/root/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
# cairo-dock &
# docky &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
#fluxbox -log "/root/.fluxbox/log" &
fluxbox &
fbpid=$!
sleep 1
{
#. /usr/share/daylight/daylightstart/launcher.sh &
conky &
terminology -b /usr/share/daylight/Daylight-linux-3-wallpapers/DayLightLogoSunSet.png &
. /usr/share/daylight/daylightstart/launcher.sh &
. /usr/share/loglauncher/startlog.sh &
} &

wait $fbpid
# or if you want to keep a log:
#exec fluxbox -log "/root/.fluxbox/log"


